branch-defaults:
  default:
    environment: mywebapi-env
    group_suffix: null
  develop:
    environment: Inlamningsuppgift-env 
global:
  application_name: Inlamningsuppgift
  branch: null
  default_ec2_keyname: null
  default_platform: .NET 8 running on 64bit Amazon Linux 2023/3.3.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
